### PR TITLE
correctly identify tranpose operator

### PR DESCRIPTION
**Pull request by Varanas**
fixes https://github.com/one-more-minute/Julia-LT/issues/144

(and sorry for the ugly commit history, no clue how to fix it...)

### CODE REVIEW

**Comment by Varanas** [comment]
I think I'll have some time to work on the highlighting soon, so there may be a big unified PR then ;)

One quite helpful resource I've found is [this](https://gist.github.com/Wilfred/f1aca44c61ed6e1df603) cheatsheet for checking the syntax highlighting. I'm not sure if all of that (or at least what's sensible - some of the proposed highlighting seems a bit much) is possible without actually parsing the source code, but the current Julia mode doesn't do all that bad.

So you could either merge this right now or wait for the bigger PR - I'll leave that up to you.

**Comment by one-more-minute** [comment]
Ok, so first, sorry for taking so long. This is a good change though, I'll patch up the history a bit and merge.

What you want to do if you want to have a go at it yourself is to do `git rebase -i head~10` (you'll probably want to point the `EDITOR` environment variable to Sublime or whatever). Then just change "pick" to "fixup" for the commits you want to hide (and/or remove them completely). When you close git will apply the changes. It's not too scary but does take a bit of getting used to.

**Comment by one-more-minute** [comment]
Merged in 13ef237d22656b74574685b26af2d5a0b112145a, thanks.

**Comment by one-more-minute** [comment]
The highlighter definitely needs some work, looking forward to that big PR if you're still working on it!

**Comment by Varanas** [comment]
Thanks for merging (and for the instructions on rebasing)!
Turns out the free time I had wasn't as free as expected, but I'm on it now.

**Pull request closed without merging**
